
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jun 24 13:27:56 CDT 2022
//----------------------------------------------------

package compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 48;
  public static final int Llave_cierre = 39;
  public static final int Or = 19;
  public static final int Llave_abre = 38;
  public static final int Fi = 9;
  public static final int Coma = 35;
  public static final int Until = 11;
  public static final int Op_booleano = 51;
  public static final int If = 7;
  public static final int T_dato = 4;
  public static final int Diferente = 31;
  public static final int Potencia = 26;
  public static final int Menor = 27;
  public static final int Else = 8;
  public static final int Read = 12;
  public static final int Corchete_c = 46;
  public static final int Error = 44;
  public static final int Asignacion = 21;
  public static final int Corchete_a = 45;
  public static final int Mayor = 29;
  public static final int Punto = 34;
  public static final int While = 20;
  public static final int Division = 25;
  public static final int Int = 15;
  public static final int Cadena = 5;
  public static final int Float = 14;
  public static final int Par_cierre = 37;
  public static final int EOF = 0;
  public static final int Not = 17;
  public static final int And = 18;
  public static final int error = 1;
  public static final int Mayor_igual = 30;
  public static final int Par_abre = 36;
  public static final int Linea = 2;
  public static final int Op_atribucion = 49;
  public static final int Do = 10;
  public static final int Op_logico = 47;
  public static final int Menor_igual = 28;
  public static final int Identificador = 41;
  public static final int Punto_coma = 33;
  public static final int Resta = 23;
  public static final int Bool = 16;
  public static final int Decimal = 43;
  public static final int Multiplicacion = 24;
  public static final int Op_incremento = 50;
  public static final int Write = 13;
  public static final int Numero = 42;
  public static final int Program = 6;
  public static final int Suma = 22;
  public static final int Main = 40;
  public static final int Igual = 32;
  public static final int Comillas = 3;
}

