
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jun 26 13:42:46 CDT 2022
//----------------------------------------------------

package compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 48;
  public static final int Llave_cierre = 36;
  public static final int Or = 16;
  public static final int Llave_abre = 35;
  public static final int Fi = 6;
  public static final int Until = 8;
  public static final int Coma = 32;
  public static final int Op_booleano = 51;
  public static final int If = 4;
  public static final int T_dato = 43;
  public static final int Diferente = 28;
  public static final int Potencia = 23;
  public static final int Menor = 24;
  public static final int Else = 5;
  public static final int Read = 9;
  public static final int Corchete_c = 46;
  public static final int Error = 41;
  public static final int Asignacion = 18;
  public static final int Corchete_a = 45;
  public static final int Mayor = 26;
  public static final int Punto = 31;
  public static final int While = 17;
  public static final int Division = 22;
  public static final int Int = 12;
  public static final int Cadena = 44;
  public static final int Float = 11;
  public static final int Par_cierre = 34;
  public static final int EOF = 0;
  public static final int Not = 14;
  public static final int And = 15;
  public static final int error = 1;
  public static final int Mayor_igual = 27;
  public static final int Par_abre = 33;
  public static final int Linea = 2;
  public static final int Op_atribucion = 49;
  public static final int Do = 7;
  public static final int Op_logico = 47;
  public static final int Menor_igual = 25;
  public static final int Identificador = 38;
  public static final int Punto_coma = 30;
  public static final int Resta = 20;
  public static final int Bool = 13;
  public static final int Decimal = 40;
  public static final int Multiplicacion = 21;
  public static final int Op_incremento = 50;
  public static final int Write = 10;
  public static final int Numero = 39;
  public static final int Program = 3;
  public static final int Suma = 19;
  public static final int Main = 37;
  public static final int Igual = 29;
  public static final int Comillas = 42;
}

